### ISSUE TITLE
Getting the share v34 warning on 1mb_segwit.

### ISSUE THREAD

**Issue by ikolubr** [jtoomim/p2pool#29]
Hi,
I'm getting the following warning on 1mb_segwit:
 >>> Warning: A MAJORITY OF SHARES CONTAIN A VOTE FOR AN UNSUPPORTED SHARE IMPLEMENTATION! (v34 with 90% support)

Anything that should I do or just go with the flow?

**Comment by frstrtr** [comment]
Update Your p2pool node from Master

**Comment by ikolubr** [comment]
so shouldn't be using the 1mb_segwit anymore?

**Comment by frstrtr** [comment]
Merged to the Master a few days ago...

**Comment by ikolubr** [comment]
Thank you boss. Problem solved.

**Comment by frstrtr** [comment]
https://forum.bitcoin.com/pools/p2pool-decentralized-dos-resistant-trustless-censorship-resistant-pool-t69932-270.html#p281350
