### ISSUE TITLE
Error "blockhash must be of length 64 (not 45"

### ISSUE THREAD

**Issue by SHlNOBI** [jtoomim/p2pool#33]
Got the  following error:

https://paste.ubuntu.com/p/jdxWyRSXRp/

**Comment by jtoomim** [comment]
I thought I fixed that issue 6 days ago with this commit:

https://github.com/jtoomim/p2pool/commit/280e48fac2d38d2fd1c31b937f1cda0bd226723b

Maybe do a git pull? What is the most recent commit listed if you do git log?

**Comment by SHlNOBI** [comment]
Oops.  my bad. You are right. I pulled  and it worked.

I set `'PERSIST = False'` in `p2pool/networks/bitcoin.py`  but  still it communicates with peers. Is  there any way i  can disable communication with  peers?

Thank you very much.

**Comment by jtoomim** [comment]
--max-conns=0
