### ISSUE TITLE
34-memfree branch - username.worker syntax parses diff as worker

### ISSUE THREAD

**Issue by chargr** [jtoomim/p2pool#34]
The recent username in this branch I dont think work as intended all the time.  username+16.999 the 999 gets treated as the worker, and the pseudo share diff gets set to 16.

A second split of the username should maybe be done separately?

Can the regex here be pre-compiled, or is class/object created on each request?
This is not the most accurate test, but the difference seems pretty consistent.

```
>>> reg = re.compile('[/+]')
>>> now = time.time(); re.split("[/+]", "worker+16.000"); print("{:.8f}".format(time.time() - now))
['worker', '16.000']
0.00003386
>>> now = time.time(); reg.split("worker+16.000"); print("{:.8f}".format(time.time() - now))
['worker', '16.000']
0.00002599
```

**Comment by jtoomim** [comment]
Thanks for pointing this out. I'll fix it.

**Comment by jtoomim** [comment]
https://github.com/jtoomim/p2pool/commit/72c72f5b50037c437c0dd5e49512a11b51d2151e
