### ISSUE TITLE
Missing fork features: bip65, csv on Bitcoin ABC 0.20.4

### ISSUE THREAD

**Issue by arruah** [jtoomim/p2pool#39]
I am running last release p2pool with Bitcoin ABC 0.20.4 full node. After start command pypy run_p2pool.py --net bitcoincash --bitcoind-config-path /opt/bch/bitcoin.conf I got the error: `You are running a coin daemon that does not support all of the forking features that have been activated on this blockchain. Consequently, your node may mine invalid blocks or may mine blocks that are not part of the Nakamoto consensus blockchain.  Missing fork features: bip65, csv`  
My bitcoin.conf
`datadir=/opt/bch/chainstate
pid=/opt/bch/bch.pid 
daemon=1
server=1
txindex=1
#debug=bench
logips=1
deprecatedrpc=estimatefee

rpcuser=*** 
rpcpassword=***
rpcbind=127.0.0.1:10933 
rpcallowip=0.0.0.0/0
rpcport=10933
bind=212.19.134.154:8333
`

**Comment by imaginaryusername** [comment]
run with `--allow-obsolete-bitcoind` and you should be fine. It's probably beneficial to remove those checks at some point since now both ABC and Unlimited no longer have those flags.

**Comment by jtoomim** [comment]
I believe this was addressed on July 5th in the stratum-autodiff branch. Once I merge that back into master, this should be resolved. The `--allow-obsolete-bitcoind` option is a good workaround for now, as imaginaryusername mentioned.

**Comment by jtoomim** [comment]
Okay, I went ahead and merged stratum-autodiff into master via PR #42. This should be solved now. If you do a `git pull`, you should no longer need the `--allow-obsolete-bitcoind` option.
