### ISSUE TITLE
Bitcoin Core testnet

### ISSUE THREAD

**Issue by dmp1ce** [jtoomim/p2pool#47]
I'm interested in generating some testnet coins on Bitcoin Core (tBTC). Is this possible with this project?

More generally, are there any testnet pools available for Bitcoin Core?

**Comment by jtoomim** [comment]
It is possible. I haven't done anything with BTC recently. Bitcoin Core has a tendency to change their API every 6 months or so in a way that breaks p2pool, and I'm not sure whether the most recent such instance of that API breaking has been fixed yet. But if that's the case, you should be able to get it to work using a slightly older version of Bitcoin Core.

If you want to solo mine on testnet, you'll need to set `PERSIST = True` in p2pool/networks/bitcoin.py or p2pool/bitcoin/networks/bitcoin.py, and then run p2pool with the `--testnet` command-line flag.

**Comment by dmp1ce** [comment]
I'll give it a try.
